version: 2.1

jobs:
  build:
    working_directory: ~/python-app-calculator
    docker:
      - image: "cimg/python:3.8.4"
    steps:
      - checkout
      - run:
           name: Install dependencies
           command: |
               pipenv install pytest
               pipenv install flask
      - run: python3 app.py
  test:
    working_directory: ~/python-app-calculator
    docker:
      - image: "cimg/python:3.6.4"
    steps:
      - checkout
      - run: python3 calculator_test.py
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build