version: 2.1
orbs:
  python: circleci/python@2.1.1
  jira: circleci/jira@1.3.1
jobs:
  run_tests:
    working_directory: ~/python-app-calculator
    docker:
      - image: "cimg/python:3.8.4"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: 
           name: Run test
           command: pytest
workflows:
  run_tests:
    jobs:
      - run_tests:
          post-steps:
            - jira/notify
            